# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='oo',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
