# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_comment_oo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='oo',
        ),
    ]
