# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comment_oo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viwes_num',
            field=models.IntegerField(default=1, verbose_name='浏览数'),
            preserve_default=False,
        ),
    ]
