# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_article_content_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_summary',
            new_name='summary',
        ),
    ]
