# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canbe_content',
            field=models.BooleanField(default=True),
        ),
    ]
