# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20170828_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='oo',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
